### PR TITLE
Gen2 common objdet

### PR DESCRIPTION
**Pull request by jonngai**

### CODE REVIEW

**Review by themarpe — APPROVED** [review]
I think we've mostly discussed and iterated on these changes offline

**Review by themarpe — CHANGES_REQUESTED** [review]
depthai-spi-library shouldn't have references to depthai-shared. 
And also the spi_api.hpp & cpp shouldn't be here neither nlohmann and other files under common directory.

Move things those things to depthai-spi-api

**Comment by jonngai** [comment]
Alright, just did some more rearranging.

**Review by themarpe — APPROVED** [review]
LGTM

**Pull request merged**
